イベント参加者がイベント編集できるように
kawazrepos/Kawaz3rd pull request #1144
Opened 2017-03-04 10:51 UTC by miio

2017-03-04 10:54 UTC, miio commented
viewのテストは「EventUpdateViewTestCase」にattendee生やしてテストするのが正解そうかねぇ？

2017-03-10 14:45 UTC, giginet requested changes
https://github.com/kawazrepos/Kawaz3rd/pull/1144/files#diff-a73b442d12fe93f0e37c807c2eacc6d4R95

attendeeが削除できないことをこの辺にテスト追加してもらって良いですか？

2017-03-10 14:46 UTC, giginet commented
変更は良さそう。

この辺のテストが全然変更されてないことを見るに、テストが薄そうなので、一度これはマージして、後日テストを追加しておきたい

2017-03-19 12:30 UTC, giginet approved these changes

2017-03-19 12:38 UTC, merged